language: python
dist: focal
stages:
  - build

# command to install dependencies
jobs:
  - stage: Build
    name: Building dependencies
    before_install:
      - echo "Initializing build"
      - python -m pip install --upgrade pip
    install:
      - pip3 install -r requirements.txt

    script:
      - ./travis_test.py
    after_success:
      - echo "SUCCESS"
