language: python
dist: focal
stages:
  - build
  - test

# command to install dependencies
jobs:
  - stage: Build
    name: Building dependencies
    before_install:
      - echo "Initializing build"
      - python -m pip install --upgrade pip
    install:
      - pip3 install --user -r requirements.txt
  - stage: Test
    name: Test scripts
    script:
      - ./travis_test.py
    after_success:
      - echo "SUCCESS"
